--- 
- hosts: 172.31.10.76
  become: yes
  tasks: 
      - name: i want to create file
        file:
          path: /home/ubuntu/myf1.txt | echo "file" >> myf1.txt
          state: touch

      - name: i want to install webserver
        apt: 
            name: apache2
            state: present   