--- 
- hosts: webserverhost 
  become: yes 
  tasks: 
      - name: i want to install java 8 on ubuntu server
        apt:
              name: "{{myjavainstallonubuntu}}"
              state: present 

        when: ansible_os_family=="Debian"

      - name: i want to install java 8 on RedHat server
        yum:
              name: "{{myjavainstallonRedHat}}"
              state: present 

        when: ansible_os_family=="RedHat"

      